CREATE TABLE IF NOT EXISTS ods_dataset_business (
business_id TEXT, 
name TEXT, 
address TEXT, 
city TEXT, 
state TEXT, 
postal_code TEXT,
latitude TEXT, 
longitude TEXT, 
stars TEXT, 
review_count TEXT, 
is_open TEXT,
categories TEXT, 
hours TEXT, 
attributes_ByAppointmentOnly TEXT,
attributes_BusinessAcceptsCreditCards TEXT, 
hours_Monday TEXT,
hours_Tuesday TEXT, 
hours_Wednesday TEXT, 
hours_Thursday TEXT, 
hours_Friday TEXT,
hours_Saturday TEXT, 
attributes_BikeParking TEXT,
attributes_RestaurantsPriceRange2 TEXT, 
attributes_CoatCheck TEXT,
attributes_RestaurantsTakeOut TEXT, 
attributes_RestaurantsDelivery TEXT,
attributes_Caters TEXT, 
attributes_WiFi TEXT, 
attributes_BusinessParking TEXT,
attributes_WheelchairAccessible TEXT, 
attributes_HappyHour TEXT,
attributes_OutdoorSeating TEXT, 
attributes_HasTV TEXT,
attributes_RestaurantsReservations TEXT, 
attributes_DogsAllowed TEXT,
hours_Sunday TEXT, 
attributes_Alcohol TEXT, 
attributes_GoodForKids TEXT,
attributes_RestaurantsAttire TEXT, 
attributes_Ambience TEXT,
attributes_RestaurantsTableService TEXT,
attributes_RestaurantsGoodForGroups TEXT, 
attributes_DriveThru TEXT,
attributes TEXT, attributes_NoiseLevel TEXT, 
attributes_GoodForMeal TEXT,
attributes_BusinessAcceptsBitcoin TEXT, 
attributes_Smoking TEXT,
attributes_Music TEXT, 
attributes_GoodForDancing TEXT,
attributes_AcceptsInsurance TEXT, 
attributes_BestNights TEXT,
attributes_BYOB TEXT, 
attributes_Corkage TEXT, 
attributes_BYOBCorkage TEXT,
attributes_HairSpecializesIn TEXT, 
attributes_Open24Hours TEXT,
attributes_RestaurantsCounterService TEXT, 
attributes_AgesAllowed TEXT,
attributes_DietaryRestrictions TEXT,
data_updated_at timestamp without time zone,
PRIMARY KEY (business_id)
);

CREATE INDEX IF NOT EXISTS dataset_business_id
    ON ods_dataset_business USING btree
    (business_id ASC NULLS LAST)
    TABLESPACE pg_default;